remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Virtual Public Sculpture]
description: [Sample site for group projects]
theme: jekyll-theme-hacker